### ISSUE TITLE
Theme Klass for modle 4

### ISSUE THREAD

**Issue by angaric** [lmsace/klass#34]
Hello. Will there be a theme for Moodle 4? So far, it only works on Moodle 3.11, but does not work on Moodle 4. We are very accustomed to the theme Klass.

**Comment by lmsace** [comment]
Hi Angaric,

Moodle version-4.0 is under development, it will be released on April 18th. 
We are testing with the dev source, we will release the Klass theme for version-4.0 once the moodle-4.0 is released.

**Comment by angaric** [comment]
Hello LMSACE!
Thank you in advance for the topic. I will wait for the release of the version for modle 4.

**Comment by prasanna-lmsace** [comment]
Klass theme released to support Moodle 4.0

**Comment by prasanna-lmsace** [comment]
Klass theme released to support Moodle 4.0.

**Comment by angaric** [comment]
Thanks!!!
